version: ' 24.0.2,'
services:
  gateway:
    build: gateway
    image: olga-shareit-gateway-image
    container_name: olga-shareit-gateway-container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: server
    image: olga-shareit-server-image
    container_name: olga-shareIt-server-container
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:shareit;MODE=PostgreSQL
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=userpassword
      - SERVER_PORT=9090

  db:
    image: postgres:15.1-alpine
    container_name: olga-shareit-db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=userpassword