CREATE TABLE IF NOT EXISTS users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(255)                            NOT NULL,
    email VARCHAR(512)                            NOT NULL,
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    description        VARCHAR(1000)                           NOT NULL,
    created_time       TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    requests_marker_id bigint references USERS (id) on update cascade on delete cascade,
    CONSTRAINT pk_requests PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS items
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR(255)                            NOT NULL,
    description VARCHAR(512)                            NOT NULL,
    available   BOOLEAN,
    owner       BIGINT references USERS (id),
    comments    BIGINT,
    requests_id bigint references requests (id) on update cascade on delete cascade,

    CONSTRAINT pk_item PRIMARY KEY (id)
);
CREATE TYPE if not exists book_status as ENUM ('WAITING', 'APPROVED', 'REJECTED');
CREATE TABLE IF NOT EXISTS bookings
(
    id         BIGINT GENERATED ALWAYS AS IDENTITY primary key,
    start_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_time   TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    item_id    bigint references ITEMS (id),
    booker_id  bigint references USERS (id),
    status     book_status                 not null,
    CONSTRAINT pk_bookings PRIMARY KEY (id)

);

CREATE TABLE IF NOT EXISTS comments
(
    id           BIGINT GENERATED ALWAYS AS IDENTITY primary key,
    text         VARCHAR(512)                NOT NULL,
    item_id      bigint references ITEMS (id),
    author_id    bigint references USERS (id),
    created_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    author_Name  VARCHAR(512),
    CONSTRAINT pk_comments PRIMARY KEY (id)
);


